namespace webapi
{
    public enum ExpenseCategory
    {
        HOUSING, FOOD, TRANSPORTATION, HEALTH, ENTERTAINMENT, DEBT,SAVING,EDUCATION,CLOTHING,PERSONAL_CARE,DONATION,
        TRAVEL,UTILITIES,GIFTS,PETS,MISCELLLANEOUS
    }
}